#+title: mkElmDerivation
[[https://img.shields.io/badge/built%20with-Haskell-8f4e8b.svg]] [[https://img.shields.io/badge/built%20for-Elm-60b6cd.svg]] [[https://img.shields.io/github/license/jeslie0/mkelmderivation.svg]] [[https://img.shields.io/github/actions/workflow/status/jeslie0/mkElmDerivation/CI.yml]]

This project is an attempt to provide a way to package elm applications with nix, with less user input required than the standard [[https://github.com/cachix/elm2nix][elm2nix]]. This project is based heavily on elm2nix and wouldn't be possible without it. There should be no need to generate any nix files using elm2nix, and no updates required when installing a new elm package. The nix expression is generated on the fly from the given =elm.json= file.

Details on how to use the flake can be found in the wiki.

Support is provided for the following:
- Ordinary elm projects;
- [[https://github.com/ryannhg/elm-spa][elm-spa]] applications;
- [[https://github.com/lydell/elm-watch][elm-watch]] applications;
- Creating =.elm= directories.

* Versions
This project currently supports version 0.19.1 of Elm.
* Updates
Currently, a GitHub action is set to run at 0000 every Sunday. This will update the three JSON files stored in the [[file:mkElmDerivation/][mkElmDerivation directory]].
