name: Update Elm Data
run-name: Updating elmData.json with newest packages
on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  Update-Elm-Data:
    runs-on: ubuntu-latest
    steps:
      - name: "Setting up Checkout"
        uses: actions/checkout@v3
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setting up Nix"
        uses: cachix/install-nix-action@v18
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            trusted-public-keys = jeslie0.cachix.org-1:orKPykG+p5gEbLe/ETPIQdAbK5WtUl2C6CZ+aVn0dy8= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://jeslie0.cachix.org https://cache.nixos.org/

      - name: Compile Haskell code with nix
        run: nix build

      - name: Update elm-hashes.json, elm-failures.json and all-packages.json
        run: nix run

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[ghactions] Update elm-hashes, elm-failures and all-packages"
          git push
